FROM python:3.11-slim

# diretório de trabalho dentro da imagem
WORKDIR /app

# copiar requirements e instalar dependências
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# copiar o código da aplicação
COPY main.py .

# porta da aplicação Flask
EXPOSE 5000

# comando para iniciar a app
CMD ["python", "main.py"]
